name: 'get-build-settings'
description: 'Uses bash scripts to find and return settings for a unity workflow to use such as project-path and build-name.'
outputs:
  project-path:
    description: 'Absolute path to the project which is the directory with your Assets folder and ProjectSettings'
    value: ${{ steps.project-path.outputs.value }}
  build-name:
    description: 'Project name derived from the project path and without the spaces, used to name build artifacts such as folders and executables'
    value: ${{ steps.build-name.outputs.value }}
runs:
  using: composite
  steps:
    - name: 'Starting CI ...'
      run: |
        NUM_COMMITS="$(git rev-list HEAD | wc -l)";

        echo "Number of commits = $NUM_COMMITS";

        if [ "$NUM_COMMITS" -eq "1" ]; then
          echo "Failed to start CI! HEAD is on initial commit. Please push more commits to start CI process.";
          exit 1
        else
          echo "Started CI successfully"
        fi
      shell: bash

    - name: 'Searching for project ...'
      id: project-path
      run: |
        RELATIVE_PROJECT_PATH="$(find . -name "ProjectSettings" -type d)/..";
        PROJECT_PATH="$(readlink -f "$RELATIVE_PROJECT_PATH")";

        echo "PROJECT_PATH=$PROJECT_PATH";

        echo "::set-output name=value::$PROJECT_PATH"
      shell: bash

    - name: 'Getting build name ...'
      id: build-name
      run: |
        BUILD_NAME="$(basename "${{ steps.project-path.outputs.value }}" | tr -d ' ')";

        echo "BUILD_NAME=$BUILD_NAME";

        echo "::set-output name=value::$BUILD_NAME"
      shell: bash