name: 'activate-unity'
description: 'Activates the Unity3D instance with the given license. The running container must have a Unity editor installed and a sym link to it in /bin.'
inputs:
  license-file:
    description: 'Path to the unity license file (.ulf) that will be created after the decryption step and will be used to activate Unity. There should be a corresponding license-file.encrypted in the same directory'
    required: true
  encryption-key:
    description: 'The encryption key secret that was used to encrypt the unity license file. This is needed to decrypt the license'
    required: true
runs:
  using: "composite"
  steps:
    - name: Validating Input
      run: |
        if [ -z "${{ inputs.license-file }}"  ]; then
          echo "Failed to activate Unity! license-file is required" >&2;
          exit 1
        fi

        if [ -z "${{ inputs.encryption-key }}" ]; then
          echo "Failed to activate Unity! encryption-key is required" >&2;
          exit 1
        fi
      shell: bash

    - name: Decrypting License
      run: |
        echo 'Decrypting License ...';
        openssl aes-256-cbc -d -pbkdf2 -in "${{ inputs.license-file }}.encrypted" -k "${{ inputs.encryption-key }}" >> "${{ inputs.license-file }}";
        echo 'License file successfully decrypted'
      shell: bash

    - name: Activating Unity
      run: |
        echo 'Activating Unity ...';
        Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile "${{ inputs.license-file }}" || exit 0;
        echo 'Unity successfully activated'
      shell: bash